var pets = [
    {
        name: 'Baxter',
        type: 'Dog',
        breed: 'Beagle',
        sex: 'Male',
        color: 'Tri-color (Black, Brown, White)',
        spayed: 'Yes',
        age: '5 Years',
        id: '34621',
        chip: '982000364789210',
        about: "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where hecan share his endless affection and playful spirit.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Luna',
        type: 'Cat',
        breed: 'Maine Coon',
        sex: 'Female',
        color: 'Grey with white markings',
        spayed: 'Yes',
        age: '3 Years',
        id: '57281',
        chip: '981120019776432',
        about: "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings. She was found as a stray and has since become a gentle and affectionate companion. Luna enjoys perching on windowsills, watching birds, and being the center of attention. She's a bit shy at first but warms up quickly, especially if you have treats! Luna would thrive in a calm environment where she can relax and be pampered like the queen she is.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Sandy',
        type: 'Dog',
        breed: 'Golden Retriever',
        sex: 'Female',
        color: 'Golden',
        spayed: 'Yes',
        age: '7 Years',
        id: '41382',
        chip: '985112004567890',
        about: "Sandy is a heartwarming Golden Retriever with a golden coat as bright as her personality. Rescued from a neglectful situation, she has shown incredible resilience and love for life. Sandy is great with children and other pets, making her an ideal family dog. She enjoys outdoor adventures, especially swimming and fetching. Sandy is looking for a forever home where she can spread her joy and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Oliver',
        type: 'Cat',
        breed: 'Siamese',
        sex: 'Male',
        color: 'Seal Point',
        spayed: 'Yes',
        age: '2 Years',
        id: '62894',
        chip: '981120025678902',
        about: "Oliver is a sleek Siamese cat with striking blue eyes and a seal point coat. Found wandering in a neighborhood, he's adapted well to shelter life but is eager for a permanent home. Oliver is vocal, expressing his thoughts freely, and enjoys interactive playtime. He's affectionate and loves to be close to his human companions, often following them around the house. Oliver would do best in a home where he can receive plenty of attention and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Max',
        type: 'Dog',
        breed: 'Labrador Retriever',
        sex: 'Male',
        color: 'Chocolate',
        spayed: 'Yes',
        age: '4 Years',
        id: '47920',
        chip: '985120031478902',
        about: "Max is a charming Chocolate Labrador with a love for life and a tail that never stops wagging. Rescued from an overcrowded shelter, Max has shown immense gratitude and loyalty to his caregivers. He is full of energy and would thrive in a home with a backyard or regular access to outdoor activities. Max is great with children and other dogs, and he's always up for a game of fetch or a leisurely walk. His ideal home would be with an active family who can match his energy and zest for life.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Daisy',
        type: 'Cat',
        breed: 'Persian',
        sex: 'Female',
        color: 'White',
        spayed: 'Yes',
        age: '6 Years',
        id: '58329',
        chip: '981120036712345',
        about: "Daisy is a stunning white Persian cat with a luxurious coat and gentle demeanor. She was surrendered by an owner who could no longer care for her. Daisy is a bit of a diva and loves being the center of attention. She enjoys being groomed and will happily sit in your lap for hours. She's not fond of loud noises or fast movements, so a quiet and calm household would be ideal. Daisy is looking for a loving home where she can be pampered and adored.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Charlie',
        type: 'Dog',
        breed: 'Dachshund',
        sex: 'Male',
        color: 'Dapple',
        spayed: 'Yes',
        age: '3 Years',
        id: '49583',
        chip: '982000367829101',
        about: "Charlie is a spirited Dapple Dachshund with a playful personality. He was found as a stray and has since shown an incredible zest for life. Charlie loves exploring, whether it's a new trail or the corners of his home. He's a bit mischievous and enjoys hiding his toys. Charlie would do well in a home with an individual or family who enjoys fun and adventure. He's small but has a big heart and a lot of love to give.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'George',
        type: 'Cat',
        breed: 'British Shorthair',
        sex: 'Male',
        color: 'Blue (Gray)',
        spayed: 'Yes',
        age: '4 Years',
        id: '61029',
        chip: '985112007651234',
        about: "George is a robust British Shorthair with a striking blue-gray coat and a calm, dignified demeanor. Rescued from a busy city environment, he's adapted well to a quieter life. George enjoys leisurely days, lounging in sunny spots, and watching the world go by. He's not overly demanding for attention but appreciates a good chin scratch and will purr loudly in response. George is a bit reserved at first but becomes a loyal companion once he feels comfortable. He would be perfect for someone seeking a low-maintenance, independent cat.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Bella',
        type: 'Dog',
        breed: 'Boxer',
        sex: 'Female',
        color: 'Fawn with white markings',
        spayed: 'Yes',
        age: '1 Year',
        id: '50824',
        chip: '982000360234567',
        about: "Bella is a spirited Boxer with a fawn coat and charming white markings. She was rescued from a neglectful situation and has shown immense love and gratitude to her caregivers. Bella is energetic and playful, enjoying activities like running and playing fetch. She's great with older children and would thrive in a home where she can be active and engaged. Bella has a big personality and would be a fantastic companion for someone who loves adventure and fun.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Sophie',
        type: 'Cat',
        breed: 'Ragdoll',
        sex: 'Female',
        color: 'Seal point with blue eyes',
        spayed: 'Yes',
        age: '1 Year',
        id: '63845',
        chip: '985112008765432',
        about: "Sophie is a young Ragdoll cat with a soft seal point coat and mesmerizing blue eyes. She was found as a kitten and raised in a foster home. Sophie is incredibly affectionate, often seeking out laps to curl up in. She's playful and enjoys interactive toys, but she's also content to relax and watch the world go by. Sophie gets along well with other pets and would be an excellent addition to a loving family or individual looking for a gentle and loving companion.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    
    {
        name: 'Max',
        type: 'Dog',
        breed: 'Beagle',
        sex: 'Male',
        color: 'Black',
        spayed: 'Yes',
        age: '3 Years',
        id: '56789',
        chip: '765432109876543',
        about: "Meet Max, a lovable Beagle with a knack for fetching balls! Max loves long walks and has boundless energy. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and cuddling on the couch. Max is looking for a loving home where he can share his endless affection and playful spirit.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Bella',
        type: 'Cat',
        breed: 'Siamese',
        sex: 'Female',
        color: 'Brown',
        spayed: 'Yes',
        age: '2 Years',
        id: '12345',
        chip: '987654321098765',
        about: "Meet Bella, a beautiful Siamese cat with striking blue eyes! Bella is a playful and affectionate companion who loves to curl up in your lap. She's great with children and enjoys lounging in sunny spots around the house. Bella is looking for a quiet home where she can be pampered and loved.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Charlie',
        type: 'Dog',
        breed: 'Golden Retriever',
        sex: 'Male',
        color: 'Golden',
        spayed: 'Yes',
        age: '4 Years',
        id: '23456',
        chip: '876543210987654',
        about: "Meet Charlie, a friendly Golden Retriever with a heart of gold! Charlie is gentle and affectionate, making him a wonderful family pet. He enjoys playing fetch and going for long walks in the park. Charlie gets along well with other dogs and loves meeting new people. He's looking for a loving home where he can be part of the family.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Luna',
        type: 'Dog',
        breed: 'Labrador Retriever',
        sex: 'Female',
        color: 'Chocolate',
        spayed: 'Yes',
        age: '5 Years',
        id: '34567',
        chip: '654321098765432',
        about: "Meet Luna, a sweet Labrador Retriever with a playful spirit! Luna loves going for runs and playing fetch in the yard. She's great with children and other dogs, making her the perfect companion for an active family. Luna is looking for a forever home where she can enjoy plenty of love and attention.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Daisy',
        type: 'Cat',
        breed: 'Maine Coon',
        sex: 'Female',
        color: 'White',
        spayed: 'Yes',
        age: '3 Years',
        id: '45678',
        chip: '543210987654321',
        about: "Meet Daisy, a majestic Maine Coon with a gentle disposition! Daisy enjoys lounging in sunbeams and birdwatching from the windowsill. She's affectionate and enjoys being brushed and pampered. Daisy gets along well with other cats and is looking for a quiet home where she can be the center of attention.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Rocky',
        type: 'Dog',
        breed: 'German Shepherd',
        sex: 'Male',
        color: 'Black and Tan',
        spayed: 'Yes',
        age: '4 Years',
        id: '67890',
        chip: '432109876543210',
        about: "Meet Rocky, a handsome German Shepherd with a protective nature! Rocky is loyal and devoted to his family, making him an excellent watchdog. He's intelligent and eager to please, making him easy to train. Rocky enjoys long walks and playing fetch in the yard. He's looking for a loving home where he can be a faithful companion.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Molly',
        type: 'Cat',
        breed: 'Persian',
        sex: 'Female',
        color: 'Silver',
        spayed: 'Yes',
        age: '2 Years',
        id: '78901',
        chip: '321098765432109',
        about: "Meet Molly, a stunning Persian cat with a regal appearance! Molly enjoys lounging in luxury and being pampered like royalty. She's calm and affectionate, making her an ideal lap cat. Molly gets along well with other cats and enjoys being the center of attention. She's looking for a loving home where she can be treated like a queen.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Buddy',
        type: 'Dog',
        breed: 'Poodle',
        sex: 'Male',
        color: 'White',
        spayed: 'Yes',
        age: '3 Years',
        id: '89012',
        chip: '210987654321098',
        about: "Meet Buddy, an adorable Poodle with a playful personality! Buddy loves going for walks and playing with toys. He's intelligent and eager to learn new tricks, making him a joy to train. Buddy enjoys spending time with people and gets along well with children and other pets. He's looking for an active family who can keep up with his playful antics.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lucy',
        type: 'Cat',
        breed: 'Ragdoll',
        sex: 'Female',
        color: 'Blue',
        spayed: 'Yes',
        age: '4 Years',
        id: '90123',
        chip: '109876543210987',
        about: "Meet Lucy, a beautiful Ragdoll with stunning blue eyes! Lucy is gentle and affectionate, making her an excellent companion. She enjoys being held and cuddled and will purr contentedly in your lap. Lucy gets along well with children and other pets and is looking for a loving home where she can be cherished.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Tiger',
        type: 'Dog',
        breed: 'Boxer',
        sex: 'Male',
        color: 'Brindle',
        spayed: 'Yes',
        age: '5 Years',
        id: '12345',
        chip: '098765432109876',
        about: "Meet Tiger, a handsome Boxer with a heart of gold! Tiger is playful and energetic, making him a great companion for outdoor adventures. He loves going for runs and playing fetch in the yard. Tiger is friendly and gets along well with people and other dogs. He's looking for an active family who can keep up with his zest for life.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Smokey',
        type: 'Cat',
        breed: 'British Shorthair',
        sex: 'Male',
        color: 'Gray',
        spayed: 'Yes',
        age: '3 Years',
        id: '23456',
        chip: '987654321098765',
        about: "Meet Smokey, a handsome British Shorthair with a dignified demeanor! Smokey enjoys lounging in comfort and watching the world go by. He's affectionate and enjoys being brushed and pampered. Smokey gets along well with children and other pets and is looking for a quiet home where he can relax and be adored.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Coco',
        type: 'Dog',
        breed: 'Labradoodle',
        sex: 'Female',
        color: 'Apricot',
        spayed: 'Yes',
        age: '4 Years',
        id: '34567',
        chip: '876543210987654',
        about: "Meet Coco, a lovable Labradoodle with a gentle nature! Coco is friendly and affectionate, making her a wonderful family pet. She enjoys going for walks and playing with toys in the yard. Coco gets along well with children and other dogs and is looking for a loving home where she can be part of the family.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Oreo',
        type: 'Cat',
        breed: 'Domestic Shorthair',
        sex: 'Male',
        color: 'Black and White',
        spayed: 'Yes',
        age: '2 Years',
        id: '45678',
        chip: '765432109876543',
        about: "Meet Oreo, a charming Domestic Shorthair with a playful spirit! Oreo loves chasing toys and lounging in sunny spots around the house. He's friendly and enjoys being petted and cuddled. Oreo gets along well with children and other cats and is looking for a loving home where he can be spoiled rotten.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Milo',
        type: 'Dog',
        breed: 'Shih Tzu',
        sex: 'Male',
        color: 'White and Brown',
        spayed: 'Yes',
        age: '3 Years',
        id: '56789',
        chip: '654321098765432',
        about: "Meet Milo, an adorable Shih Tzu with a cheerful disposition! Milo loves going for walks and exploring new places. He's playful and enjoys romping around in the yard. Milo is friendly and gets along well with people and other dogs. He's looking for a loving home where he can be pampered and adored.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lucky',
        type: 'Cat',
        breed: 'Siberian',
        sex: 'Female',
        color: 'Tabby',
        spayed: 'Yes',
        age: '4 Years',
        id: '67890',
        chip: '543210987654321',
        about: "Meet Lucky, a playful Siberian cat with a mischievous streak! Lucky enjoys chasing toys and climbing to new heights. She's curious and enjoys exploring her surroundings. Lucky gets along well with children and other pets and is looking for an adventurous family who can keep up with her antics.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Shadow',
        type: 'Dog',
        breed: 'Border Collie',
        sex: 'Male',
        color: 'Black and White',
        spayed: 'Yes',
        age: '5 Years',
        id: '78901',
        chip: '432109876543210',
        about: "Meet Shadow, a smart Border Collie with boundless energy! Shadow loves learning new tricks and playing interactive games. He's highly trainable and excels at agility and obedience. Shadow is friendly and gets along well with people and other dogs. He's looking for an active family who can provide plenty of mental and physical stimulation.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Misty',
        type: 'Cat',
        breed: 'Himalayan',
        sex: 'Female',
        color: 'Cream',
        spayed: 'Yes',
        age: '3 Years',
        id: '89012',
        chip: '321098765432109',
        about: "Meet Misty, a beautiful Himalayan cat with a calm demeanor! Misty enjoys lounging in quiet corners and being petted and brushed. She's affectionate and enjoys spending time with her human companions. Misty gets along well with children and other cats and is looking for a peaceful home where she can relax and be adored.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Sam',
        type: 'Dog',
        breed: 'Jack Russell Terrier',
        sex: 'Male',
        color: 'White with Brown',
        spayed: 'Yes',
        age: '4 Years',
        id: '90123',
        chip: '109876543210987',
        about: "Meet Sam, an energetic Jack Russell Terrier with a playful personality! Sam loves going for walks and exploring his surroundings. He's curious and enjoys digging and sniffing out new scents. Sam is friendly and gets along well with people and other dogs. He's looking for an active family who can keep up with his adventures.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Molly',
        type: 'Cat',
        breed: 'Bengal',
        sex: 'Female',
        color: 'Leopard Spotted',
        spayed: 'Yes',
        age: '2 Years',
        id: '23456',
        chip: '987654321098765',
        about: "Meet Molly, a playful Bengal cat with a wild streak! Molly loves climbing and leaping around the house. She's curious and enjoys exploring her surroundings. Molly gets along well with children and other pets and is looking for an adventurous family who can provide plenty of enrichment and excitement.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Oscar',
        type: 'Dog',
        breed: 'Dachshund',
        sex: 'Male',
        color: 'Red',
        spayed: 'Yes',
        age: '3 Years',
        id: '34567',
        chip: '876543210987654',
        about: "Meet Oscar, a charming Dachshund with a big personality! Oscar loves going for walks and exploring new smells. He's playful and enjoys chasing toys in the yard. Oscar is friendly and gets along well with people and other dogs. He's looking for a loving home where he can be the center of attention.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Angel',
        type: 'Cat',
        breed: 'Scottish Fold',
        sex: 'Female',
        color: 'Blue and White',
        spayed: 'Yes',
        age: '4 Years',
        id: '45678',
        chip: '765432109876543',
        about: "Meet Angel, a sweet Scottish Fold with a gentle disposition! Angel enjoys lounging in cozy beds and watching the world go by. She's affectionate and enjoys being petted and cuddled. Angel gets along well with children and other cats and is looking for a loving home where she can be pampered and adored.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
]